### ISSUE TITLE
This example is not working with 64x32 screen

### ISSUE THREAD

**Issue by suvi-ngaige** [micooke/squix78_OLED#2] opened 2018-05-09 13:30 UTC
I have tested this code for 64x32 screen. but it fails to display anything on OLED.
in SquixOLED_Screentest example folder, file name  angry_cookie_64x32_xbm.h  having 

	const uint8_t width = 36;
	const uint8_t height = 32;
I am confused about it width should be 64?

I think there are three commands, which are changes according to the screensize.
SETCOMPINS
SETCONTRAST
SETMULTIPLEX
after this command oled requires hex number as command.
for 64x32 , after SETMULTIPLEX command 
controller should send 0x1F .
Not getting the value for other two commands.
Please help me with this.

**Comment by micooke** [comment] 2018-05-09 22:42
Hi @suvi-ngaige. First up, i dont mind as i don't get a lot of traffic on this repo but this is a duplicate of issue #1.
I can definitely update this repo if you want as the paging framework that @squix78 developed is really nice, however if you just want something that works for a 64x32 ssd1306 can i recommend @olikraus's u8g2 library https://github.com/olikraus/U8g2_Arduino which supports this screen and sees a lot more development than any of mine (its what I use now). Another alternative is my sparkfun_OLED repo which works.

**Comment by micooke** [comment] 2018-06-06 23:33
I havent had any time to do this yet, still tidying up some other work and been on holidays. Ill try to get back to this, hopefully in the next week or two

**Comment by micooke** [comment] 2018-07-25 03:05
@suvi-ngaige - regarding the following lines:
```
const uint8_t width = 36;
const uint8_t height = 32;
```
The squix78 OLED library allows you to write to a portion of the screen, and the angry_cookie image is only 36 pixels wide so this width is correct. This differs from the sparkfun OLED libray where you need to write the full buffer for an image - so good question/pickup!

This should be resolved from 9369085e3864af96990e01590716ff37683d6616. The issue is that i was trying to create a uniform interface for the sparkfun and squix78 libraries to make it easier to maintain both, and i left some hangover code that is specific to my sparkfun OLED library (support for SH1107).
Now that the u8g2 library supports all the drivers im interested in, i will stall development on these two libraries.

**Closed as completed by micooke** 2018-07-25 03:05 UTC
Labels: bug, duplicate
